//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitLabelConverter.Console.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SBU (Use Drop Down)")]
        public string SbuColumnName {
            get {
                return ((string)(this["SbuColumnName"]));
            }
            set {
                this["SbuColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Attn:")]
        public string AttnColumnName {
            get {
                return ((string)(this["AttnColumnName"]));
            }
            set {
                this["AttnColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Department")]
        public string DepartmentColumnName {
            get {
                return ((string)(this["DepartmentColumnName"]));
            }
            set {
                this["DepartmentColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Item Number")]
        public string ItemNumberColumnName {
            get {
                return ((string)(this["ItemNumberColumnName"]));
            }
            set {
                this["ItemNumberColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPC number (Can\'t have any spaces)")]
        public string UpcColumnName {
            get {
                return ((string)(this["UpcColumnName"]));
            }
            set {
                this["UpcColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kit Name")]
        public string KitNameColumnName {
            get {
                return ((string)(this["KitNameColumnName"]));
            }
            set {
                this["KitNameColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("In-Store Date")]
        public string InStoreDateColumnName {
            get {
                return ((string)(this["InStoreDateColumnName"]));
            }
            set {
                this["InStoreDateColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Set Date")]
        public string SetDateColumnName {
            get {
                return ((string)(this["SetDateColumnName"]));
            }
            set {
                this["SetDateColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Destroy Date")]
        public string DestroyDateColumnName {
            get {
                return ((string)(this["DestroyDateColumnName"]));
            }
            set {
                this["DestroyDateColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPC Encoded")]
        public string UpcEncodedColumnName {
            get {
                return ((string)(this["UpcEncodedColumnName"]));
            }
            set {
                this["UpcEncodedColumnName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apparel;Consumables;Corporate Operations;Entertainment;Fuel;Grocery;Hardiness;Har" +
            "dlines;Health and Wellness;Health Wellness;Home;Seasonal;Sign Logistics;Structur" +
            "al;Toys;Walmart Services")]
        public string ValidSbuNames {
            get {
                return ((string)(this["ValidSbuNames"]));
            }
            set {
                this["ValidSbuNames"] = value;
            }
        }
    }
}
